import * as cdk from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as cr from 'aws-cdk-lib/custom-resources';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as iam from 'aws-cdk-lib/aws-iam';
import { Construct } from 'constructs';

export interface StackTables {
  stateTable:    dynamodb.Table;
  samlAppsTable: dynamodb.Table;
  systemConfig:  dynamodb.Table;
  adminUsers:    dynamodb.Table;
  auditLog:      dynamodb.Table;
}

interface DataStackProps extends cdk.StackProps {
  stage: string;
}

export class DataStack extends cdk.Stack {
  public readonly tables:              StackTables;
  public readonly appSecret:           secretsmanager.Secret;
  public readonly bootstrapAdminSecret:secretsmanager.Secret;
  public readonly jwtSigningSecret:    secretsmanager.Secret;
  public readonly hostingBucket:       s3.Bucket;

  constructor(scope: Construct, id: string, props: DataStackProps) {
    super(scope, id, {
      ...props,
      description: 'Entra Verified ID — DynamoDB tables, Secrets Manager secrets, and S3 hosting bucket',
    });
    const { stage } = props;

    // ── DynamoDB ────────────────────────────────────────────────────────────

    const commonTableProps: Partial<dynamodb.TableProps> = {
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      pointInTimeRecoverySpecification: { pointInTimeRecoveryEnabled: true },
      encryption: dynamodb.TableEncryption.AWS_MANAGED,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    };

    this.tables = {
      stateTable: new dynamodb.Table(this, 'StateTable', {
        ...commonTableProps,
        tableName:    `EntraVerifiedID-${stage}`,
        partitionKey: { name: 'requestId', type: dynamodb.AttributeType.STRING },
        timeToLiveAttribute: 'ttl',
      }),

      samlAppsTable: new dynamodb.Table(this, 'SamlAppsTable', {
        ...commonTableProps,
        tableName:    `VerifiedIDSamlApps-${stage}`,
        partitionKey: { name: 'appId', type: dynamodb.AttributeType.STRING },
      }),

      systemConfig: new dynamodb.Table(this, 'SystemConfigTable', {
        ...commonTableProps,
        tableName:    `EntraVerifiedIDSystemConfig-${stage}`,
        partitionKey: { name: 'pk', type: dynamodb.AttributeType.STRING },
        sortKey:      { name: 'sk', type: dynamodb.AttributeType.STRING },
      }),

      adminUsers: new dynamodb.Table(this, 'AdminUsersTable', {
        ...commonTableProps,
        tableName:    `EntraVerifiedIDAdminUsers-${stage}`,
        partitionKey: { name: 'username', type: dynamodb.AttributeType.STRING },
      }),

      auditLog: new dynamodb.Table(this, 'AuditLogTable', {
        ...commonTableProps,
        tableName:    `EntraVerifiedIDAuditLog-${stage}`,
        partitionKey: { name: 'pk', type: dynamodb.AttributeType.STRING },
        sortKey:      { name: 'sk', type: dynamodb.AttributeType.STRING },
        timeToLiveAttribute: 'expires_at',
      }),
    };

    // ── Secrets Manager ─────────────────────────────────────────────────────

    // Application secrets — populated by the onboarding wizard, not at deploy time.
    this.appSecret = new secretsmanager.Secret(this, 'AppSecret', {
      secretName:  `EntraVerifiedID/${stage}/app`,
      description: 'Entra app registration credentials and signing key - populated by the setup wizard',
      secretObjectValue: {
        clientId:              cdk.SecretValue.unsafePlainText('PENDING_SETUP'),
        clientSecret:          cdk.SecretValue.unsafePlainText('PENDING_SETUP'),
        eamClientId:           cdk.SecretValue.unsafePlainText('PENDING_SETUP'),
        eamClientSecret:       cdk.SecretValue.unsafePlainText('PENDING_SETUP'),
        callbackSecret:        cdk.SecretValue.unsafePlainText('PENDING_SETUP'),
        eamSigningKey:         cdk.SecretValue.unsafePlainText('PENDING_SETUP'),
        eamKid:                cdk.SecretValue.unsafePlainText('PENDING_SETUP'),
      },
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    // Bootstrap admin — random credentials generated at deploy time, consumed once by the wizard.
    this.bootstrapAdminSecret = new secretsmanager.Secret(this, 'BootstrapAdminSecret', {
      secretName:  `EntraVerifiedID/${stage}/bootstrap-admin`,
      description: 'One-time admin bootstrap credentials. Deleted by wizard after first login.',
      generateSecretString: {
        secretStringTemplate: JSON.stringify({ username: 'admin' }),
        generateStringKey:    'password',
        excludePunctuation:   true,
        passwordLength:       32,
      },
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    // JWT signing key — generated by a custom resource at deploy time.
    this.jwtSigningSecret = new secretsmanager.Secret(this, 'JwtSigningSecret', {
      secretName:  `EntraVerifiedID/${stage}/jwt-signing-key`,
      description: 'HMAC-SHA256 key for signing admin session JWTs',
      generateSecretString: {
        secretStringTemplate: JSON.stringify({ algorithm: 'HS256' }),
        generateStringKey:    'key',
        excludePunctuation:   false,
        passwordLength:       64,
      },
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    // ── S3 hosting bucket (private, for .well-known/* and config.json) ──────

    this.hostingBucket = new s3.Bucket(this, 'HostingBucket', {
      bucketName:          `entra-vid-hosting-${this.account}-${stage}`,
      blockPublicAccess:   s3.BlockPublicAccess.BLOCK_ALL,
      encryption:          s3.BucketEncryption.S3_MANAGED,
      versioned:           true,
      enforceSSL:          true,
      removalPolicy:       cdk.RemovalPolicy.RETAIN,
    });

    // ── Outputs ──────────────────────────────────────────────────────────────

    new cdk.CfnOutput(this, 'OutStateTable',      { value: this.tables.stateTable.tableName });
    new cdk.CfnOutput(this, 'OutSamlAppsTable',   { value: this.tables.samlAppsTable.tableName });
    new cdk.CfnOutput(this, 'OutSystemConfig',    { value: this.tables.systemConfig.tableName });
    new cdk.CfnOutput(this, 'OutAdminUsers',      { value: this.tables.adminUsers.tableName });
    new cdk.CfnOutput(this, 'OutAuditLog',        { value: this.tables.auditLog.tableName });
    new cdk.CfnOutput(this, 'AppSecretArn',        { value: this.appSecret.secretArn });
    new cdk.CfnOutput(this, 'BootstrapSecretArn',  { value: this.bootstrapAdminSecret.secretArn });
    new cdk.CfnOutput(this, 'HostingBucketName',   { value: this.hostingBucket.bucketName });
  }
}
